- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/login.go
- cmd/esc/cli/login_test.go
- If creds are missing, return a friendly message instructing the user to log in
- If the active account is not a cloud account, return a message indicating that the backend is not supported
Fixes #89.
> cli: do not panic on missing/invalid creds

- cmd/esc/cli/esc.go
- cmd/esc/cli/login.go
- cmd/esc/cli/login_test.go
Do not reference the `esc` CLI when it is being embedded in another tool.
> cli: fix login error messages

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/env_init.go
- cmd/esc/cli/testdata/env-init-conflict.yaml
- cmd/esc/cli/testdata/env-init-diags.yaml
- cmd/esc/cli/testdata/env-init-ok.yaml
- cmd/esc/cli/testdata/env-set-invalid.yaml
- cmd/esc/cli/testdata/env-set-secret-error.yaml
- cmd/esc/cli/testdata/env-set-secret.yaml
- cmd/esc/cli/testdata/env-set.yaml
If this flag is specified, the initial definition of the environment is read from the given file. If the filename is `-`, contents are read from `stdin`. If the initial definition contains errors, the environment is still created but is left empty.
Related to #91.
> cli: add a `-f` flag to `env init`

- CHANGELOG.md
- CHANGELOG_PENDING.md
- cmd/esc/cli/login.go
- cmd/esc/cli/testdata/login-logout.yaml
If no backend is specified or available via existing Pulumi creds, default to https://api.pulumi.com.
Fixes #100.
> cli: default to api.pulumi.com for login

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_set.go
- cmd/esc/cli/testdata/env-set.yaml
After interpretation by the shell, `env set foo bar ""` passes an empty string as the value to set. The YAML parser treats the empty string as "no document" and doesn't return any content from Unmarshal. Work around this by treating "no document" as an empty string _literal_ (which is likely the intent).
Fixes #109.
> cli: do not panic in `env set foo bar ""`

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/logout.go
- cmd/esc/cli/testdata/env-login-gh100.yaml
- cmd/esc/cli/workspace/credentials.go
- When running `login` in an environment where there are no existing credentials, also set the current `pulumi` account if using shared creds
- When logging out, check to see if we're actually logged in before attempting to log out.
Fixes #100.
> cli: fix more login bugs

- CHANGELOG_PENDING.md
- ast/expr.go
- eval/eval.go
- eval/eval_validate.go
- eval/expr.go
- eval/testdata/eval/omnibus/env.yaml
- eval/testdata/eval/omnibus/expected.json
- eval/value.go
- internal/util/path.go
- value.go
These changes add two new builtins, `fn::fromBase64` and `fn::fromJSON`. The former decodes a base64-encoded string into a binary string and the latter decodes a JSON string into a value.
Fixes #103.
Fixes #104.
> eval: add fn::from{Base64,JSON}

- eval/testdata/eval/unicode/env.yaml
- eval/testdata/eval/unicode/expected.json
- syntax/encoding/yaml.go
It was possible for the byte-offset calcuation in positionIndex.pos to end up in an infinite loop if the column as calculated by `uniseg` differed from the column as calculated by the YAML parser. These changes eliminate that possibility by terminating the loop if there are no more bytes in the line being processed.
These changes also add a small optimization to avoid dealing with Unicode Text Segmentation for lines that are entirely ASCII.
> encoding: fix an infinite loop

- cmd/esc/cli/esc.go
Create a copy of the open/run command structs before adding them as top-level aliases. This is done because `AddCommand` mutates fields on the Command struct, changing its parent, which causes docs to not be generated correctly from the pulumi/pulumi CLI.
Part of https://github.com/pulumi/pulumi/issues/14237
> cli: fix generated CLI docs for pulumi/pulumi

- schema/arrays_test.go
- schema/booleans_test.go
- schema/nulls_test.go
- schema/numbers_test.go
- schema/objects_test.go
- schema/schema.go
- schema/strings_test.go
> Testing improvements for schema package

- Makefile
- analysis/analysis.go
- analysis/common_test.go
- analysis/describe.go
- analysis/describe_test.go
- analysis/traversal.go
- analysis/traversal_test.go
- eval/expr.go
- eval/testdata/eval/builtin-combine/expected.json
- eval/testdata/eval/builtin-errs/expected.json
- eval/testdata/eval/cycle/expected.json
- eval/testdata/eval/duplicate-keys/expected.json
- eval/testdata/eval/escape-keys/expected.json
- eval/testdata/eval/imports/expected.json
- eval/testdata/eval/interp/expected.json
- eval/testdata/eval/invalid-access/expected.json
- eval/testdata/eval/literals/expected.json
- eval/testdata/eval/merge-replace/expected.json
- eval/testdata/eval/merge-unknown/expected.json
- eval/testdata/eval/omnibus/expected.json
- eval/testdata/eval/open-unknown/expected.json
- eval/testdata/eval/open/expected.json
- eval/testdata/eval/schema-error/expected.json
- eval/testdata/eval/schema/expected.json
- eval/testdata/eval/unicode/expected.json
- expr.go
These changes add a package to aid in authoring tools that use the results of Check/Open as a jumping-off point for analyzing environments. This package currently supports finding the expression at a given source position and describing the entity at a given source position.
> analysis: add a package for static analysis

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_run.go
- cmd/esc/cli/testdata/run.yaml
This PR adds support for projecting configuration properties as temporary files, based on a new well-known block called `files`. For each property, a temporary file is created containing the property value, and an environment variable is set pointing to the temporary file. Note that the file contents may be dynamically generated using interpolation.
This feature is designed for a key scenario of projecting a `kubeconfig` file based on a Pulumi environment. Here's how that would work:
Define an environment:
```yaml
imports:
- dev-sandbox
values:
files:
KUBECONFIG: |
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: LS0tLS1...
server: https://....gr7.us-west-2.eks.amazonaws.com
name: arn:aws:eks:us-west-2:616138583583:cluster/mycluster
contexts:
- context:
cluster: …
```
> Support for file projection in `run` command

- .gitignore
- .vscode/extensions.json
- .vscode/tasks.json
This PR contributes a basic vscode project configuration for ease of
use.
The project files do the following:
1. Configure the default Build Task (⇧⌘B) to run `make build`.
2. Configure the default Test Task to run `make test`.
3. Recommend the "Go" vscode extensions when the project is opened.
See: https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Global/VisualStudioCode.gitignore
> vscode project files

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/testdata/env-get-all-value-dotenv.yaml
- cmd/esc/cli/testdata/env-get-all-value-shell.yaml
- cmd/esc/cli/testdata/env-rm-ok.yaml
- cmd/esc/cli/testdata/open-dotenv.yaml
- cmd/esc/cli/testdata/open-shell.yaml
- cmd/esc/cli/testdata/run.yaml
- environment.go
These changes add helpers for fetching the environment variables and temporary files defined by an environment. The former are sourced from the `environmentVariables` top-level property and the latter from the `files` top-level property. In both cases, nested properties with scalar values are coerced to strings and nested properties with non-scalar values are ignored.
These changes also use these helpers to extend support for the `files` property to `open`.
Fixes #118.
> esc, cli: helpers for well-known properties

- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/prepare.go
Other tools that consume the ESC CLI can use this method to extract environment variables, create temporary files, and discover associated secrets from an environment.
> cli: export PrepareEnvironment

- ast/expr.go
- syntax/diags.go
- syntax/diags_test.go
- Remove some unused exports from syntax.Diagnostic{,s}
- Add coverage for Diagnostics.Error
> syntax: diags coverage

- CHANGELOG_PENDING.md
- analysis/common_test.go
- ast/expr.go
- cmd/esc/cli/cli_test.go
- eval/crypt.go
- eval/crypt_test.go
- eval/eval.go
- eval/eval_test.go
- eval/expr.go
- eval/testdata/crypt/omnibus.ciphertext.yaml
- eval/testdata/crypt/omnibus.plaintext.yaml
- eval/testdata/crypt/open.ciphertext.yaml
- eval/testdata/crypt/open.plaintext.yaml
- eval/testdata/crypt/trivia.ciphertext.yaml
- eval/testdata/crypt/trivia.plaintext.yaml
- eval/testdata/eval/ciphertext-invalid/env.yaml
- eval/testdata/eval/ciphertext-invalid/expected.json
- eval/testdata/eval/ciphertext/env.yaml
- eval/testdata/eval/ciphertext/expected.json
- eval/testdata/eval/interp/env.yaml
- eval/testdata/eval/interp/expected.json
- eval/testdata/eval/plaintext/env.yaml
- eval/testdata/eval/plaintext/expected.json
- syntax/encoding/testdata/yaml/top-level-array/decoded.json
- syntax/encoding/testdata/yaml/top-level-array/encoded.yaml
- syntax/encoding/yaml.go
- syntax/encoding/yaml_test.go
- syntax/syntax.go
- syntax/walk.go
These changes add support for encrypting and decrypting static secrets in environment definitions. Encryprtion and decryption is handled as a pre-evaluation pass. The parser expects secrets to be decrypted prior to parsing, and will issue errors if it detects encrypted secrets.
Encrypted secrets are represented in the document by calls to `fn::secret` of the form
```yaml
fn::secret:
ciphertext: <base64-encoded value>
```
In order to support this representation, `fn::secret` now requires that its argument is a string literal.
> def: support secret encryption + decryption

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/testdata/env-set-secret.yaml
- value.go
When this flag is passed, static secrets will be shown in plaintext rather than ciphertext.
> cli: support --show-secrets in `env get`

- eval/eval.go
- eval/testdata/eval/builtin-combine/expected.json
- eval/testdata/eval/builtin-errs/expected.json
- eval/testdata/eval/cycle/expected.json
- eval/testdata/eval/invalid-access/expected.json
- eval/testdata/eval/nested-unknowns-secrets/env.yaml
- eval/testdata/eval/nested-unknowns-secrets/expected.json
- eval/testdata/eval/open/expected.json
- eval/testdata/eval/schema-error/expected.json
- eval/testdata/eval/schema/expected.json
- eval/value.go
Do not treat object and array literals that include unknown or secret
elements as unknown or secret themselves. Instead, leave it up to the
consumer of the literal to handle unknownness and secretness
appropriately (i.e. by combining the unknownness and secretness of each
leaf value the consumer observes).
For example, the following object definition no is no longer unknown
during check or secret during eval:
```yaml
foo:
bar: 42
baz:
fn::secret:
ciphertext: AjIAEJFDIe==
```
Instead, it is partially-known during check:
```yaml
foo:
bar: 42
baz: [unknown]
```
And partially-secret during eval:
```yaml
foo:
bar: 42
baz: [secret]
```
But when passed to `fn::toJSON`, the result of the call would be unknown
in check or secret in eval b/c of the nested unknown/secret.
Fixes …
> eval: improve unknown/secret for complex literals 

- cmd/esc/cli/env_open.go
- cmd/esc/cli/prepare.go
- cmd/esc/cli/testdata/env-get-all-value-dotenv.yaml
- cmd/esc/cli/testdata/env-get-all-value-shell.yaml
- cmd/esc/cli/testdata/env-get-all.yaml
Setting this option will redact secrets in environment variables. Only respected if Pretend is true.
> cli: add a Redact field to PrepareOptions

- eval/eval.go
- eval/testdata/eval/import-cycle-2/a.yaml
- eval/testdata/eval/import-cycle-2/b.yaml
- eval/testdata/eval/import-cycle-2/env.yaml
- eval/testdata/eval/import-cycle-2/expected.json
- eval/testdata/eval/import-cycle/env.yaml
- eval/testdata/eval/import-cycle/expected.json
Issue errors for cyclic imports. Cycles are detected by tracking whether or not an environment is being evaluated in the imports map. If an environment is imported while it is being evaluated, then there is a cycle.
> eval: detect cyclic imports

- cmd/esc/cli/client.go
- cmd/esc/cli/esc.go
This method, `NewClient`, returns an API client that uses the same credentials as the `esc` CLI. This is primarily useful for integration into other tools.
> cli: add a convenience method for client creation

- CHANGELOG_PENDING.md
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/builtin-combine/expected.json
- eval/testdata/eval/builtin-errs/expected.json
- eval/testdata/eval/ciphertext-invalid/expected.json
- eval/testdata/eval/ciphertext/expected.json
- eval/testdata/eval/cycle/expected.json
- eval/testdata/eval/duplicate-keys/expected.json
- eval/testdata/eval/escape-keys/expected.json
- eval/testdata/eval/import-cycle-2/expected.json
- eval/testdata/eval/import-cycle/expected.json
- eval/testdata/eval/imports/expected.json
- eval/testdata/eval/interp/expected.json
- eval/testdata/eval/invalid-access/expected.json
- eval/testdata/eval/literals/expected.json
- eval/testdata/eval/merge-replace/expected.json
- eval/testdata/eval/merge-unknown/expected.json
- eval/testdata/eval/nested-unknowns-secrets/expected.json
- eval/testdata/eval/omnibus/expected.json
- eval/testdata/eval/open-unknown/expected.json
- eval/testdata/eval/open/expected.json
- eval/testdata/eval/plaintext/expected.json
- eval/testdata/eval/reserved-keys/expected.json
- eval/testdata/eval/schema-error/expected.json
- eval/testdata/eval/schema/expected.json
- eval/testdata/eval/secret-objects/env.yaml
- eval/testdata/eval/secret-objects/expected.json
- eval/testdata/eval/unicode/expected.json
- value.go
The first commit demonstrates the issue, secret objects (and arrays) were not being marked as secret when evaluating fromJSON.
> fromJSON: Mark nested structures as secret if the JSON string is secret

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_open.go
- cmd/esc/cli/testdata/open-yaml.yaml
Adds support for yaml format in `esc open`. 
Added test to verify.
Fixes [#195](https://github.com/pulumi/esc/issues/195).
> Add support for yaml output format

- CHANGELOG.md
- CHANGELOG_PENDING.md
Also fill-in CHANGELOG for v0.6.1.
We need another release of `esc` so we can depend on it from `pulumi/pulumi`.
> chore: CHANGELOG for v0.6.2

- CHANGELOG_PENDING.md
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/import-merge-2/a.yaml
- eval/testdata/eval/import-merge-2/b.yaml
- eval/testdata/eval/import-merge-2/c.yaml
- eval/testdata/eval/import-merge-2/env.yaml
- eval/testdata/eval/import-merge-2/expected.json
- eval/testdata/eval/import-merge/a.yaml
- eval/testdata/eval/import-merge/b.yaml
- eval/testdata/eval/import-merge/c.yaml
- eval/testdata/eval/import-merge/env.yaml
- eval/testdata/eval/import-merge/expected.json
- eval/testdata/eval/imports/expected.json
- eval/testdata/eval/merge-base/a.yaml
- eval/testdata/eval/merge-base/env.yaml
- eval/testdata/eval/merge-base/expected.json
- eval/testdata/eval/merge-unknown/expected.json
- eval/value.go
- expr.go
These changes fix the merging of values that have already been merged.
During evaluation, merged values are represented by _chains_. Each value
`v` maintains a reference to its _base_ value--i.e. the value with which
it has been merged--if any. For example, consider the following values,
where `repr` is the value's data and `base` is the value's base:
```
A: (repr: { foo: B }, base: None)
B: (repr: "bar", base: None)
C: (repr: { foo: D, zed: E }, base: None)
D: (repr: "baz", base: None)
E: (repr: "qux", base: None)
```
When merging `C` onto `A`, `C`'s base will be set to `A` and`D`'s base
will be set to `B`:
```
A: (repr: { foo: B }, base: None)
B: (repr: "bar", base: None)
C: (repr: { foo: D, zed: E }, base: A)
D: (repr: "baz", base: B)
E: (repr: "qux", base: None)
```
Now introduce the …
> eval: fix merging of merged values

- ast/environment.go
- ast/environment_test.go
- ast/expr.go
- ast/interpolation.go
- ast/interpolation_test.go
- ast/property.go
- ast/property_test.go
- ast/testdata/parse/invalid-interpolations/env.yaml
- ast/testdata/parse/invalid-interpolations/expected.json
- ast/testdata/parse/invalid-join/env.yaml
- ast/testdata/parse/invalid-join/expected.json
- ast/testdata/parse/invalid-open/env.yaml
- ast/testdata/parse/invalid-open/expected.json
- ast/testdata/parse/invalid-plaintext/env.yaml
- ast/testdata/parse/invalid-plaintext/expected.json
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/invalid-access-load/expected.json
Allow the parser to recover from errors and return its best possible AST. This is the first step towards allowing evaluation of environments that contain parse errors, which is vital for live analysis.
> ast: error recovery

- CHANGELOG_PENDING.md
- ast/expr.go
- ast/testdata/parse/invalid-plaintext/expected.json
- eval/eval.go
- eval/eval_test.go
- eval/expr.go
- eval/testdata/eval/invalid-access-load/expected.json
- eval/testdata/eval/invalid-join/env.yaml
- eval/testdata/eval/invalid-join/expected.json
- eval/testdata/eval/invalid-open/env.yaml
- eval/testdata/eval/invalid-open/expected.json
- eval/testdata/eval/invalid-plaintext/env.yaml
- eval/testdata/eval/invalid-plaintext/expected.json
These changes add support for evaluating environment decls that contain parse errors. All current parse errors manifest as missing nodes. These changes add a `missingExpr` expression type to handle those cases. Missing expressions are treated as `any`-typed null literals.
The primary benefit of these changes is that they enable type checking environments with parse errors (i.e. calling `CheckEnvironment`). This is important for live analysis scenarios.
> eval: evaluate after parse errors

- ast/property.go
- ast/testdata/parse/invalid-interpolations/env.yaml
- ast/testdata/parse/invalid-interpolations/expected.json
- eval/eval.go
- eval/testdata/eval/invalid-access-load/env.yaml
- eval/testdata/eval/invalid-access-load/expected.json
Rather than treat empty interpolations as having no accessors, treat them as having a single accessor that is the empty string. This is still invalid--and we issue an error--but allows us to more faithfully represent the syntactical structure of the document.
> ast: better handling for empty interpolations

- ast/interpolation.go
- ast/interpolation_test.go
- ast/property.go
- ast/testdata/parse/invalid-interpolations/expected.json
- eval/testdata/eval/invalid-access-load/expected.json
The property access parser has been getting increasingly gnarly, and will continue to do so as it evolves to handle accessor ranges. These changes refactor the parser for simplicity and clarity. As a nice side-effect, they also improve some error reporting.
> ast: clarify property name parser

- CHANGELOG_PENDING.md
- eval/eval.go
- eval/testdata/eval/import-merge-2/expected.json
- eval/testdata/eval/import-merge/expected.json
- eval/testdata/eval/imports/expected.json
- eval/testdata/eval/invalid-access/expected.json
- eval/testdata/eval/omnibus/expected.json
The schema returned by the evaluator did not represent the schema of the final, merged value. These changes correct that mistake.
> eval: merge final environment schema

- CHANGELOG_PENDING.md
- ast/expr.go
- ast/interpolation.go
- ast/interpolation_test.go
- ast/property.go
- ast/testdata/parse/invalid-interpolations/env.yaml
- ast/testdata/parse/invalid-interpolations/expected.json
- cmd/esc/cli/testdata/open-json-error.yaml
- eval/eval.go
- eval/expr.go
- eval/testdata/eval/builtin-combine/expected.json
- eval/testdata/eval/builtin-errs/expected.json
- eval/testdata/eval/cycle/expected.json
- eval/testdata/eval/imports/expected.json
- eval/testdata/eval/interp/expected.json
- eval/testdata/eval/invalid-access-load/expected.json
- eval/testdata/eval/invalid-access/expected.json
- eval/testdata/eval/merge-base/expected.json
- eval/testdata/eval/merge-unknown/expected.json
- eval/testdata/eval/nested-unknowns-secrets/expected.json
- eval/testdata/eval/omnibus/expected.json
- eval/testdata/eval/open-unknown/expected.json
- eval/testdata/eval/open/expected.json
- eval/testdata/eval/schema-error/expected.json
- eval/testdata/eval/schema/expected.json
- eval/testdata/eval/secret-objects/expected.json
- expr.go
- syntax/encoding/yaml.go
- syntax/syntax.go
These changes add support for reporting ranges for accessors in single-line flow strings (i.e. single-line strings that are not quoted).
Multi-line strings are quite a bit more complicated to support. The string we get from the YAML parser has already been processed to remove indentation, fold newlines, etc., so its bytes do not represent the bytes in the original file. We will want to add support for these strings in the future, but doing so is something of an open problem.
> ast: ranges for accessors in single-line flow strings

- CHANGELOG_PENDING.md
- ast/property.go
- ast/testdata/parse/invalid-interpolations/expected.json
- eval/testdata/eval/invalid-access-load/expected.json
These changes refine the ranges for errors encountered when parsing properties. When possible, errors will now be associated with the erroneous accessor rather than the parent string.
> ast: refine ranges for property errors

- CHANGELOG.md
- CHANGELOG_PENDING.md
- analysis/describe_test.go
- analysis/traversal_test.go
- cmd/esc/cli/cli_test.go
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/context-interpolation/env.yaml
- eval/testdata/eval/context-interpolation/expected.json
Add support for injecting contextual execution information and enable it to be used to interpolate in the environment attributes.
IE:
```
context = {
"attr1": { "value": "foo" }, 
"attr2": "bar"
}
```
can be used as:
```
values:
sample: ${context.attr1.value}-${context.attr2}
```
would generate:
```
{
"sample": "foo-bar"
}
```
> Add support for execution context data for interpolation

- ast/expr.go
Avoid nil-pointer-in-non-nil-interface errors by making exprPosition generic over its argument type.
Fixes #243.
> ast: fix a nil deref

- ast/expr.go
- ast/expr_test.go
The change in 0d2eda1 did not fix the panic condition, which occurs if the underlying *StringExpr is nil. Check for nil using reflection, and add a test to verify the fix.
> Fix a nil deref, take two

- ast/expr.go
- eval/eval.go
If an import declaration has a nil name, we can't process it any further, so we can terminate early.
Also, change the "nil in interface" check in `exprPosition` to use `IsZero` instead of `IsNil`, as the latter may panic if the value in the interface is not a pointer (or other nillish type).
> eval: check for a nil import name

- CHANGELOG_PENDING.md
- analysis/common_test.go
- analysis/describe_test.go
- analysis/traversal_test.go
- cmd/esc/cli/cli_test.go
- environment.go
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/<yaml>/a.yaml
- eval/testdata/eval/<yaml>/env.yaml
- eval/testdata/eval/<yaml>/expected.json
- eval/testdata/eval/context-interpolation/env.yaml
- provider.go
- Splitting `context.environment` into `rootEnvironment` and `currentEnvironment` (potentially just `environment`)
- When evaluating an anonymous environment, the `rootEnvironment` will evaluate to the rootest non anonymous environment for the imported environments (wont propagate to the root)
Having these 3 envs:
```
imports:
- imported
values:
root:
currentEnvironment: ${context.currentEnvironment.name}
rootEnvironment: ${context.rootEnvironment.name}
imports:
- child
values:
imported:
currentEnvironment: ${context.currentEnvironment.name}
rootEnvironment: ${context.rootEnvironment.name}
values:
child:
currentEnvironment: ${context.currentEnvironment.name}
rootEnvironment: ${context.rootEnvironment.name}
``` 
In the case the `root` env is anonymous, it resolves:
```
{
"child": { …
```
> Handle anonymous environments when injecting it to the context

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_init.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/testdata/env-edit-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-get-all.yaml
- cmd/esc/cli/testdata/env-init-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-rm-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-set-revision-or-tag.yaml
- cmd/esc/cli/testdata/open-json.yaml
These changes add support to the CLI for getting or opening environments at specific revisions or tags using the familiar `name:revision-or-tag` syntax.
> cli: add revision/tag support to get and open

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_run.go
- cmd/esc/cli/testdata/run.yaml
`Command.Exec` does not close these streams if they are redirected. We rely on `Close` to flush any remaining output.
> cli: flush std{out,err} after `esc run`

- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/env_log.go
- cmd/esc/cli/testdata/env-log.yaml
If a revision has tags, display them after the revision number ala `git log`.
> cli: add tags to `env log` output

- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_log.go
- cmd/esc/cli/pager/pager.go
- cmd/esc/cli/pager/system.go
- cmd/esc/cli/style/dark_style.go
- cmd/esc/cli/style/light_style.go
- cmd/esc/cli/style/style.go
- cmd/esc/cli/style/stylist.go
- go.mod
- go.sum
Use the same styling as is used for rendering top-level headers in the output of `esc env get`.
> cli: make `env log` prettier

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_version.go
- cmd/esc/cli/env_version_ls.go
- cmd/esc/cli/env_version_rm.go
- cmd/esc/cli/env_version_tag.go
- cmd/esc/cli/testdata/env-version-tag.yaml
- go.mod
These changes add commands for managing version tags:
- `esc env version tag` creates, describes, or updates a version tag
- `esc env version rm` deletes a version tag
- `esc env version ls` lists version tags
> cli: add commands for managing version tags

- CHANGELOG_PENDING.md
- cmd/esc/cli/env.go
- cmd/esc/cli/env_diff.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/style/chroma.go
- cmd/esc/cli/templates.go
- cmd/esc/cli/templates/env-diff.tmpl
- cmd/esc/cli/testdata/env-diff.yaml
- go.mod
- go.sum
These changes add a command, `esc env diff`, for displaying the differences between environment revisions. By default, the output includes both value and definition diffs. Diffs between the value as rendered in different formats (e.g. `shell`, `json`, etc.) can also be displayed.
> cli: add a command for diffing revisions

- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_init.go
- cmd/esc/cli/env_log.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/env_version.go
- cmd/esc/cli/env_version_ls.go
- cmd/esc/cli/env_version_rm.go
- cmd/esc/cli/env_version_show.go
- cmd/esc/cli/env_version_tag.go
- cmd/esc/cli/pager/pager.go
- cmd/esc/cli/testdata/env-edit-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-get-all.yaml
- cmd/esc/cli/testdata/env-init-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-rm-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-set-revision-or-tag.yaml
- cmd/esc/cli/testdata/env-version-tag.yaml
- cmd/esc/cli/testdata/open-json.yaml
These changes add an `env version show` command to display a specific version of an environment and replace the `:` name/version separator with `@`.
> cli: env version show + replace ':' with '@'

- cmd/esc/cli/env_diff.go
- cmd/esc/cli/env_version_tag.go
`env diff` and `env version tag` both accept arguments that imply an environment name. In the case of `env diff`, this is the version to use for comparison; for `env version tag` it is the version to target with the tag. In both cases, document that the syntax for these arguments is `@version` (but continue to accept a bare version).
> cli: prefer '@version' when env name is implied

- cmd/esc/cli/env.go
- cmd/esc/cli/env_diff.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_init.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/env_version.go
- cmd/esc/cli/env_version_history.go
- cmd/esc/cli/env_version_tag.go
- cmd/esc/cli/env_version_tag_ls.go
- cmd/esc/cli/env_version_tag_rm.go
- cmd/esc/cli/testdata/env-diff.yaml
Instead of only allowing `esc env diff` to compare different versions of the same environment, allow it to compare different environments altogether.
Most of the delta here is some rather mechanical refactoring to encapsulate the (org, env, version) tuple that identifies an environment in a type.
> cli: allow comparing different envs

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/testdata/env-edit-file.yaml
This flag allows the user to provide a file from which to read the new environment definition. The flag has the same behavior as the `-f` flag for `env init`.
> cli: add a `-f` flag to `env edit`

- CHANGELOG_PENDING.md
- cmd/esc/cli/env.go
- cmd/esc/cli/env_rollback.go
- cmd/esc/cli/testdata/env-rollback.yaml
`esc env rollback` rolls the environment definition back to a specific version.
Note that this can fail if the target of the rollback imports environments that have changed in incompatible ways. Imports should be versioned in order to prevent this.
> cli: add a rollback command

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_rm.go
- cmd/esc/cli/env_rollback.go
- cmd/esc/cli/env_set.go
- Resolves https://github.com/pulumi/esc/issues/313
- Adds revision into GetEnvironment and UpdateEnvironment client functions
- Manually tested via PSP + dev stack, client returns revision successfully
> Adding Revision to esc client

- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
All versioning-related APIs now live under `/versions`, and the shape of the revision-related APIs has changed somewhat.
This has the nice side-effect of removing an API call when using tagged versions.
> cli: move to new versioning API routes

- eval/eval.go
Rather than panicking in this case, report the internal error and return an invalid access.
I haven't been able to construct a repro for this case, but we've been hitting it in the field.
> eval: internal error on nil receiver

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_version.go
- cmd/esc/cli/env_version_history.go
- cmd/esc/cli/env_version_retract.go
- cmd/esc/cli/env_version_tag_ls.go
- cmd/esc/cli/testdata/env-get-all.yaml
- cmd/esc/cli/testdata/env-init-ok.yaml
- cmd/esc/cli/testdata/env-version-history.yaml
- cmd/esc/cli/testdata/env-version-retract.yaml
This command retracts a specific revision of an environment. A retracted revision can no longer be read or opened. Retracting a revision also updates any tags that point to the retracted revision to instead point to a replacement revision. If no replacement is specified, the latest non-retracted revision preceding the revision being retracted is used as the replacement.
The revision pointed to by the `latest` tag may not be retracted. To retract the latest revision of an environment, first update the environment with a new definition.
> cli: add env version retract

- CHANGELOG_PENDING.md
- cmd/esc/cli/env.go
- cmd/esc/cli/env_version.go
- cmd/esc/cli/env_version_rollback.go
- cmd/esc/cli/testdata/env-version-rollback.yaml
Move the rollback command under the `version` command for the sake of consistency.
> cli: env rollback -> env version rollback

- analysis/describe_test.go
- analysis/traversal_test.go
- cmd/esc/cli/cli_test.go
- eval/eval.go
- eval/eval_test.go
- eval/testdata/eval/ciphertext-show-secrets/env.yaml
- eval/testdata/eval/ciphertext-show-secrets/expected.json
- eval/testdata/eval/ciphertext-show-secrets/overrides.json
- eval/testdata/eval/ciphertext-show-secrets/test-base.yaml
These changes allow clients to request that CheckEnvironment decrypt static secrets rather than treating their contents as unknown. This allows clients to more reliably implement `showSecrets` by supplying a decrypter and setting the `showSecrets` flag to `true`. To acheive equivalent behavior without these changes, the client must decrypt secrets in environment definitions prior to calling `CheckEnvironment` and as part of `LoadEnviroment`.
Part of #347.
> eval: allow secret decryption in CheckEnvironment

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_set.go
- cmd/esc/cli/testdata/env-set-secret.yaml
`esc env set --secret` requires that its argument is a string literal. While this is consistent with the requirements of the evaluator, it is somewhat less than ergonomic for CLI users, who must surround numeric or boolean values in both single and double quotes:
```console
esc env set my-env --secret foo.bar '"1234"'
```
These changes detect non-string scalar values passed to `esc env set --secret` and automatically coerce these values to strings. Non-scalar values are passed through to the evaluator as-is, which will report that the argument must be a string literal.
Fixes #296.
> [cli] Stringify scalar secrets

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/env_get.go
- cmd/esc/cli/testdata/env-get-all.yaml
These changes plumb support for showing _all_ static secrets through
`esc env get` (rather than only those secrets immediately present in
the environment being read directly; i.e. including secrets from
imported environments).
Note that this support is latent, and the fix will not be user-visible
until supporting code is deployed to the ESC API.
Part of https://github.com/pulumi/esc/issues/347.
> cli: deeper support for show-secrets in env get 

- ast/environment.go
The `parseField` function was not initializing `v` on an error case, which could led to subsequent code trying to use an uninitialized pointer and causing a panic.
Fix https://github.com/pulumi/esc/issues/298
> Initialize field before use

- eval/eval.go
- eval/testdata/eval/ciphertext-import/env.yaml
- eval/testdata/eval/ciphertext-import/expected.json
- eval/testdata/eval/ciphertext-import/test-base.yaml
These changes fix a bug in `CheckEnvironment` when `showSecrets` is
`false`. In this case, if the environment loader supplied a decrypter
for an imported environment, the imported environment's secrets would be
decrypted, violating the `showSecrets` contract. In order to address
this issue, these changes store and propagate the value of `showSecrets`
in the evaluator's context.
> eval: fix showSecrets in CheckEnvironment

- CHANGELOG_PENDING.md
- cmd/esc/cli/login.go
- cmd/esc/cli/login_test.go
Fixes https://github.com/pulumi/esc/issues/367.
If the pulumi credentials have a current account saved, but that account's access key has expired `httpstate.Current` will return `nil, nil`. `getCachedCredentials` did not correctly handle this `nil, nil` result.
> Handle login.Current returning nil

- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
```bash
❯ esc env init test2/esc/hello
Environment created: test2/esc/hello
❯ esc env version tag test2/esc/hello@mytag 1
❯ esc env version tag ls test2/esc/hello
latest
Revision 1
Last updated at 2024-08-21 16:16:26.844 -0500 CDT by  <syeh2>
mytag
Revision 1
Last updated at 2024-08-21 16:16:35.263 -0500 CDT by  <syeh2>
```
> Update to match changes to API

- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
Adds methods for the anonymous open env routes so that the Pulumi CLI can use them
> Add anonymous open environment routes

- CHANGELOG.md
- cmd/esc/cli/env.go
- cmd/esc/cli/env_ls.go
```bash
$ esc env ls -p {project}
```
> [env] add project filter to ls command

- eval/eval_test.go
- eval/testdata/eval/bench/a.yaml
- eval/testdata/eval/bench/b.yaml
- eval/testdata/eval/bench/c.yaml
- eval/testdata/eval/bench/d.yaml
- eval/testdata/eval/bench/e.yaml
- eval/testdata/eval/bench/env.yaml
- eval/testdata/eval/bench/f.yaml
- eval/testdata/eval/bench/g.yaml
- eval/testdata/eval/bench/h.yaml
- eval/testdata/eval/bench/i.yaml
- eval/testdata/eval/bench/j.yaml
- eval/testdata/eval/bench/k.yaml
- eval/testdata/eval/bench/l.yaml
- eval/testdata/eval/bench/m.yaml
- eval/testdata/eval/bench/n.yaml
- eval/testdata/eval/bench/o.yaml
- eval/testdata/eval/bench/p.yaml
- eval/testdata/eval/bench/q.yaml
- eval/testdata/eval/bench/r.yaml
- eval/testdata/eval/bench/s.yaml
- eval/testdata/eval/bench/t.yaml
- eval/testdata/eval/bench/u.yaml
- eval/testdata/eval/bench/v.yaml
- eval/testdata/eval/bench/w.yaml
- eval/testdata/eval/bench/x.yaml
- eval/testdata/eval/bench/y.yaml
- eval/testdata/eval/bench/z.yaml
These changes add four benchmarks for the evaluator: one for the evalutator itself, one focused on `fn::open`, one focused on environment loading, and one for the entire stack. Each benchmark uses the same set of environments with different parameters for the time taken by an `fn::open` call or an environment load.
Local results are below.
```
goos: darwin
goarch: arm64
pkg: github.com/pulumi/esc/eval
cpu: Apple M1 Max
BenchmarkEval-10           	    196	  6029274 ns/op	4626576 B/op	  23578 allocs/op
BenchmarkEval-10           	    195	  6051825 ns/op	4625788 B/op	  23576 allocs/op
BenchmarkEval-10           	    195	  6041508 ns/op	4625803 B/op	  23576 allocs/op
BenchmarkEval-10           	    195	  6070728 ns/op	4625819 B/op	  23577 allocs/op
BenchmarkEval-10           	    194 …
```
> eval: add benchmarks

- CHANGELOG_PENDING.md
- analysis/common_test.go
- ast/environment.go
- ast/expr.go
- cmd/esc/cli/client/client_test.go
- eval/eval.go
- eval/eval_test.go
- eval/expr.go
- eval/value.go
- schema/objects.go
- schema/objects_test.go
- schema/schema.go
- schema/schema_test.go
These changes improve evaluation performance by memoizing exported values and merged object keys and avoiding copies when building object schemas.
This gives a tremendous improvement in execution time for evaluation-dominated scenarios, but results in little to no change for open- or load-dominated scenarios. However, the memoization and avoidance of copies cuts memory usage in half in all cases.
Strictly speaking, this is a breaking change for consumers of the `schema` package, but I think that it is worth taking given the improvements.
Local benchmark results:
```
goos: darwin
goarch: arm64
pkg: github.com/pulumi/esc/eval
cpu: Apple M1 Max
BenchmarkEval-10           	    453	  2566938 ns/op	2204129 B/op	  18883 allocs/op
BenchmarkEval-10           	    468	  2586703 ns/op	2204146 B/op …
```
> eval: performance improvements

- cmd/esc/cli/gen_docs.go
Similar to https://github.com/pulumi/pulumi/pull/17536, this change adjusts the path used to generate links between ESC CLI docs to match their new location at `/docs/esc/cli`.
>  Adjust the link path used in generated CLI docs

- CHANGELOG_PENDING.md
- go.mod
- go.sum
Depends on https://github.com/pulumi/pulumi/pull/17541 , which implements the fix in pulumi. Then we can update the dependency to pull in the fix
Fixes https://github.com/pulumi/esc/issues/401
```
❯ go run ./cmd/esc login
Manage your Pulumi ESC environments by logging in.
Run `esc login --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
Error: problem logging in: EOF
exit status 1
❯ go run ./cmd/esc login
Error: could not determine current cloud: reading Pulumi credentials: failed to read Pulumi credentials file. Please fix or delete invalid credentials file: '/Users/sean/.pulumi/credentials.json': invalid character 'a' looking for beginning of value
exit status 1
```
> Bump pulumi to v3.137.0

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_get.go
- cmd/esc/cli/testdata/env-get-definition-error.yaml
- cmd/esc/cli/testdata/env-get-definition.yaml
Fixes https://github.com/pulumi/esc/issues/415
Adds a `--definition` flag to the get command. we already have a `--value` command to only output the value, so I figured the `--definition` flag makes sense. open to other suggestions though
```
❯ go run ./cmd/esc env get temp2/abc/importer --definition --value json
Error: `--value` and `--definition` flags cannot be used together
exit status 1
❯ go run ./cmd/esc env get temp2/abc/importer --definition
imports:
- abc/envvars
...
```
> Add --definition to get to print definition

- cmd/esc/cli/env_rm.go
This is the only use of `sdk/go/common/env` outside of `pulumi/pulumi`, and it's easily removed by inlining the name of the relevant environment variable. Since we already do this in a few other places (e.g. backend URL lookup), this commit makes the change and breaks the dependency.
> Remove dependency on `pulumi` `sdk/go/common/env`

- CHANGELOG_PENDING.md
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
Fixes https://github.com/pulumi/esc/issues/370
When updating an env with an invalid definition, `UpdateEnvironmentWithRevision` should return no error but with diagnostics
Because of this issue, we previously wouldn't reach [here](https://github.com/pulumi/esc/blob/0a8fc4100f4cce21f9b45faa9ef379d100718696/cmd/esc/cli/env_edit.go#L127) (which requires non-error but with diagnostics), but with this change, now we can, because `UpdateEnvironmentWithRevision` will now return no error but with diagnostics on invalid definitions
When updating an env with an invalid definition:
Before:
```
❯ go run ./cmd/esc env edit test3/abc/ghi
Error: updating environment definition: [0]
Diags: yaml: line 2: mapping values are not allowed in this context
exit status 1
```
Now:
```
❯ go run ./cmd/esc env edit …
```
> Fix diagnostic messages on update environment

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_rotate.go
`go run ./cmd/esc env rotate temp2/abc/rotate`
Rotated and opened the env. Also tested with various `-f` options
Does not accept `@version`
```
❯ go run ./cmd/esc env rotate temp2/abc/yo@asdf
Error: the rotate command does not accept environments at specific versions
exit status 1
```
> Add rotate command

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_rotate.go
Tested with passing paths
```
go run ./cmd/esc rotate delme/abc/yo ab cd
```
With invalid path
```
❯ go run ./cmd/esc env rotate delme/abc/yo abc ....
Error: '....' is an invalid property path: expected property path to start with a name or index
exit status 1
```
> Add paths to rotate

- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_rotate.go
The Rotate API no longer does an open, so this adjusts the esc CLI accordingly
> Separate open environment from rotate

- CHANGELOG_PENDING.md
- eval/eval.go
- eval/testdata/eval/inline-reference/env.yaml
- eval/testdata/eval/inline-reference/expected.json
- eval/testdata/eval/inline-reference/foo/bar.yaml
The `environments` top level key is now reserved for inline environment references. This allows you to implicitly import and reference a value in another environment by accessing `${environments.$project.$env...}`. This desugars into something like `${imports["$project/$env"]...}` and behaves as if the environment was imported with merge:false.
This is followed up by #444
> inline environment references

- eval/eval.go
- eval/testdata/eval/inline-reference-rotateOnly/expected.json
- eval/testdata/eval/rotate-state/expected.json
- schema/objects.go
- schema/schema.go
The rotateOnly flag is now represented by a list of property names on the parent object schema, similar to `required`.
During schema compilation, the flag is internally pushed down onto the properties, and is accessible via their IsRotateOnly() method.
> schema: rotateOnly flag is now represented as a list of property names

- eval/value.go
- eval/value_test.go
The intent of `containsObservableUnknowns` is to allow `evaluateBuiltinRotate` tolerate rotateOnly values being unknown when not rotating.  RotateOnly indicates that `open` will not read those values, so it's okay for them to be unknown.  
During rotation, `rotate` will read all inputs, so all inputs must be known at that time.
Unfortunately the equality isn't correct, because it's returning false for unknown, non-rotateOnly values, which allows for an unknown value to be unexpectedly passed into the provider's Rotate method.
Fixes https://github.com/pulumi/pulumi-service/issues/26101
> eval: containsObservableUnknowns is incorrect for non-rotateOnly inputs

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_rotate.go
Example output with a complete error, partial error, and successful rotation
> Release Rotate CLI

- CHANGELOG_PENDING.md
- ast/environment.go
- ast/expr.go
- ast/testdata/parse/invalid-invocation/env.yaml
- ast/testdata/parse/invalid-invocation/expected.json
- ast/testdata/parse/invalid-invocation2/env.yaml
- ast/testdata/parse/invalid-invocation2/expected.json
Currently when a fn expr is invalid we fall back to parsing it as an object, which results in an object containing a `fn::` key, which is otherwise illegal, instead of the expected call.  This PR makes these incorrect usages emit syntax errors so that it's easier for the user to identify the mistake ahead of time, instead of after discovering that the function wasn't called.
Case 1 - having an additional key in a fn call:
```
values:
foo:
fn::builtin: ...
anotherKey: "oops"
```
Case 2 - having a fn:: key as a toplevel key in values:
```
values:
fn::open::provider: ...
```
Resolves #447
> ast: syntax errors for invalid fn invocation

- eval/eval.go
- eval/testdata/eval/inline-reference-cycle/bad/bad.yaml
- eval/testdata/eval/inline-reference-cycle/env.yaml
- eval/testdata/eval/inline-reference-cycle/expected.json
We track the lifetime of each environments import evaluations to detect cyclic imports.  Right now this is tracked while we're evaluating the imports decl.
However, #443 introduced a way to import environment values inline.  Once we've started evaluating the environment values root, we currently stop tracking whether the environment is evaluating because we're done with all the imports.
The result of this is that a cyclic environment reference will look up the environment name in the imports map and won't detect that it is still evaluating.  Since the cached value in the imports map hasn't been set yet (since the environment hasn't finished evaluating) we return nil as the value.  This results in a panic when we try to actually access the value.
To fix this, I'm just hoisting the …
> fix panic when evaluating cyclic environment references

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_set.go
- cmd/esc/cli/testdata/env-set-string-error.yaml
- cmd/esc/cli/testdata/env-set-string.yaml
Add a `--string` flag to `env set` to treat given value as a string
> cli: add a --string flag to env set

- cmd/esc/cli/env.go
- cmd/esc/cli/gen_docs.go
Looks like most of the commands in ESC already just use the cobra args functions and RunE. But `env` was using `cmdutil.NoArgs` and `gen-docs` was using `cmdutil.ExactArgs` and `Run` instead of `RunE`.
> Use cobra args functions instead of cmdutil

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env_ls.go
- Fixes https://github.com/pulumi/esc/issues/472
- Introduces ListOrganizationEnvironments API into the client
- Currently used API ListEnvironments only takes in orgName as a filter, so if no such org exists, it returns an empty array and a 2XX
- Therefore make the list command select between ListOrganizationEnvironments and ListEnvironments  based on whether org name is provided
- ListOrganizationEnvironments returns proper 404 when org is not found, which results in CLI command returning error code 1 properly
- Adjusted client tests
- Manually tested using `esc env ls; echo $?`
- `esc env real-org; echo $?` returns 0, whether or not it has environments
- `esc env non-existing-org; echo $?` returns 1, and prints an error message `Error: listing environments: [404] Not Found: …
> Adding proper errors to list environments

- CHANGELOG_PENDING.md
- cmd/esc/cli/login.go
- cmd/esc/cli/login_test.go
- cmd/esc/cli/workspace/credentials.go
- Fixes https://github.com/pulumi/esc/issues/473
- Makes ESC CLI always prefer env var `PULUMI_BACKEND_URL` over backend url saved into the account
- If backendURL is overridden, then login will run and look for `PULUMI_ACCESS_TOKEN` env var, falling back to accounts if it's not specified
- Manually tested, the scenario in ticket now works
- Manually tested case when invalid backend URL is set via env var (or if user never logged in with that backend), user will see `Error: no credentials. Please run `esc login` to log in.`
> Ensuring env var is always taken over account backend url

- CHANGELOG_PENDING.md
- eval/crypt.go
- eval/crypt_test.go
We should only decrypt secrets under `values`. This fixes decryption errors when we have invalid ciphertexts under invalid top-level keys (which we don't validate for)
> Don't decrypt secrets from invalid top-level keys

- CHANGELOG_PENDING.md
- cmd/esc/cli/env.go
This pull request includes a change to the `writeYAMLEnvironmentDiagnostics` function in the `cmd/esc/cli/env.go` file. The change addresses a security issue identified by gosec G115 by modifying how the `hcl.NewDiagnosticTextWriter` is instantiated.
* [`cmd/esc/cli/env.go`](diffhunk://#diff-35037241ba6b265db4f58db9fa451f9e62c2b545e7236e1ee1ae0a5bdf7fdaeaL343-R347): Modified the `writeYAMLEnvironmentDiagnostics` function to instantiate `hcl.NewDiagnosticTextWriter` with a width of 0 initially, and then conditionally reinstantiate it with the specified width if it is greater than 0, addressing gosec G115.
> chore(gosec): Fixes gosec G115

- go.mod
- go.sum
This pull request includes a small change to the `go.mod` file. The change updates the version of the `github.com/golang-jwt/jwt/v5` dependency from `v5.2.1` to `v5.2.2` to ensure the project uses the latest version.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L108-R108): Updated `github.com/golang-jwt/jwt/v5` dependency from `v5.2.1` to `v5.2.2`.
> chore(deps): jwt-go update to v5.2.2 for dependabot

- .github/workflows/pr-tests.yaml
- .github/workflows/publish-prerelease.yaml
- .github/workflows/publish-release.yaml
- .github/workflows/publish-snapshot.yaml
- .github/workflows/stage-publish.yml
- .github/workflows/stage-test.yml
This pull request includes updates to several GitHub Actions workflow files to specify permissions for various jobs. These changes ensure that the workflows have the necessary permissions to perform their tasks, such as publishing releases and packages.
Permissions updates:
* [`.github/workflows/pr-tests.yaml`](diffhunk://#diff-3916175353da81b6cca987b01c9e9615428e7601e00c805533c7844c1528658fR9-R10): Added `read-all` permissions to the workflow.
* [`.github/workflows/publish-prerelease.yaml`](diffhunk://#diff-0f355e6081d174f772bc6161eace6e05b7af4da4dfad5a3b4510e6bb41b4c693R11-R14): Added `contents: write` and `packages: write` permissions needed for publishing releases and packages.
* [`.github/workflows/publish-release.yaml`](diffhunk://#diff-a6abdc5a2c99b75dc521141aa12b5dc8381ff914e4a7e43 …
> chore(github-workflows): Adding permissions to github workflows

- .github/workflows/publish-prerelease.yaml
- .github/workflows/publish-release.yaml
- .github/workflows/publish-snapshot.yaml
This pull request includes updates to the permissions in several GitHub workflow files to ensure they have the necessary read and write access for various actions. The most important changes include adding specific read permissions for different GitHub features.
Permissions updates in workflow files:
* [`.github/workflows/publish-prerelease.yaml`](diffhunk://#diff-0f355e6081d174f772bc6161eace6e05b7af4da4dfad5a3b4510e6bb41b4c693R14-R25): Added read permissions for actions, attestations, checks, deployments, discussions, issues, pages, pull-requests, repository-projects, statuses, and security-events.
* [`.github/workflows/publish-release.yaml`](diffhunk://#diff-a6abdc5a2c99b75dc521141aa12b5dc8381ff914e4a7e4383062c94e6f8a4fc7L15-R26): Added read permissions for actions, attestations, …
> chore(actions): fixing permissions for github actions

- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/esc.go
- cmd/esc/cli/login.go
- cmd/esc/cli/login_test.go
- cmd/esc/cli/workspace/config.go
Fix https://github.com/pulumi/pulumi-service/issues/27575
A goal of Project Hockeystick is to have new Pulumi users to be able to trial premium Pulumi features immediately; as a part of this, we would want new Pulumi users to have their `esc` usage directly hook into to the trial org with Premium features enabled, rather than their individual org.
For details on the project, see the epic: https://github.com/pulumi/home/issues/3910
1. Adds integration against the new `GetDefaultOrg` API call: https://github.com/pulumi/pulumi-service/pull/27461
2. Adds fallback logic to make the API call if `~/.pulumi/config` does not have default org set for the given backend;
3. Move fallback logic of falling back to the individual org to after the API call is made.
> Enable client lookup of default orgs if not locally set

- .github/workflows/pr-tests.yaml
- .github/workflows/stage-lint.yml
- .github/workflows/stage-test.yml
The last release failed with a permission problem: https://github.com/pulumi/esc/actions/runs/14630282476
The publish-release workflow [uses a subjob for lint](https://github.com/pulumi/esc/blob/7d7a7cc1acbeb7418e5da19b81af49cf840ce991/.github/workflows/publish-release.yaml#L30).  the lint job says it wants [permissions: read-all](https://github.com/pulumi/esc/blob/7d7a7cc1acbeb7418e5da19b81af49cf840ce991/.github/workflows/stage-lint.yml#L6) but the parent workflow [has a subset of permissions](https://github.com/pulumi/esc/blob/7d7a7cc1acbeb7418e5da19b81af49cf840ce991/.github/workflows/publish-release.yaml#L12-L26). I suspect that the `models: read` permission is new and didn't used to be included in `read-all`.  Now that it is the parent permissions no longer cover what the child says …
> CI: reduce scope of permissions of test & lint jobs

- cmd/esc/cli/cli_test.go
- eval/eval_test.go
- go.mod
- go.sum
The newer version of this module adds map- and slice-specific packages
to ease some of the boilerplate (e.g. `slices.Map(s, ...)` can replace
`fx.Map(fx.IterSlice(s), ...))`.
These changes also fix some etag vs. revision tag conflation in the CLI
tests.
> chore: update to fx/v2

- cmd/esc/cli/env_run.go
- go.mod
- go.sum
Use a more memory-efficient fork of the Aho-Corasick replacer (with a slightly nicer API to boot).
> cli: use a more efficient fork of aho-corasick

- CHANGELOG_PENDING.md
- Makefile
Fixes https://github.com/pulumi/esc/issues/520
We were using the wrong path for setting version during build, which was causing `esc version` to not output anything.
> Fix esc version

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_run.go
- cmd/esc/cli/testdata/run-no-env-error-with-separator.yaml
- cmd/esc/cli/testdata/run-no-env-error.yaml
Fixes #478 
This PR checks ensures that the first argument for _run_ is always an environment. This is required for when `--` is used since in the current behavior will threat the first argument after `--` as the environment.
**Before:**
**After:**
> Always expect environment name as first argument for run 

- cmd/esc/cli/gen_docs.go
This PR improves the front matter metadata for all ESC CLI command documentation pages to enhance SEO and search discoverability.
- **Title Enhancement**: Added " | CLI commands" suffix to all ESC CLI command page titles
- **Meta Descriptions**: Added standardized `meta_desc` field with contextual descriptions for ESC commands
- **Aliases**: Added proper redirect aliases to frontmatter
- **SEO Optimization**: Custom descriptions for 8 common ESC commands (esc, esc env, esc login, etc.) with fallback pattern
- Improved search engine discoverability of ESC CLI documentation
- Better page titles in search results and browser tabs
- Standardized meta descriptions instead of auto-generated excerpts
- Enhanced SEO performance for ESC CLI documentation
- Updates the `generateMetaDescription()` …
> Improve ESC CLI command page metadata for better SEO

- cmd/esc/cli/env_ls.go
- cmd/esc/cli/testdata/env-ls.yaml
Sorting does not take the project name into account. These changes fix
the behavior of `env ls` so that environments are sorted by
organization, then project, then name.
> cli: fix sorting in env ls

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/env_version_rollback.go
- cmd/esc/cli/testdata/env-edit-editor-invalid-draft.yaml
- cmd/esc/cli/testdata/env-edit-editor-ok-draft.yaml
- cmd/esc/cli/testdata/env-set-draft.yaml
- cmd/esc/cli/testdata/env-version-rollback-draft.yaml
- cmd/esc/cli/testdata/login-logout.yaml
Automatically submit change request for simplicity. The console does the same currently.
The flag is hidden for now while the feature and APIs are in preview.
Closes https://github.com/pulumi/pulumi-service/issues/28046
Examples:
```
> esc env set example/g values.example abc2 --draft
Change request created: a9b6ab9b-54b6-4ad6-8236-0d0d1e4eba48
Change request URL: https://app.pulumi.com/pulumipus-org/esc/example/g/change-requests/a9b6ab9b-54b6-4ad6-8236-0d0d1e4eba48
Change request submitted
> esc env edit example/g --draft
Change request created: bc15bae8-2afb-4a63-8d50-ffefef7fbe77
Change request URL: https://app.pulumi.com/pulumipus-org/esc/example/g/change-requests/bc15bae8-2afb-4a63-8d50-ffefef7fbe77
Change request submitted
> esc env version rollback example/g@1 --draft
Change …
```
> [approvals] Add draft flag to env set, edit, version rollback

- .github/workflows/pr-tests.yaml
- .github/workflows/publish-prerelease.yaml
- .github/workflows/publish-release.yaml
- .github/workflows/publish-snapshot.yaml
- .github/workflows/stage-publish.yml
- .github/workflows/stage-test.yml
These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …
> chore: replace GH secrets with ESC

- CHANGELOG_PENDING.md
- cmd/esc/cli/env_get.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/fs.go
- cmd/esc/cli/testdata/env-set-file.yaml
This PR adds supports for `--file <path>` modifier in `esc env set`. 
This modifier will read the file in <path> and, if it's a valid string content, will use that to set the value of the specified key.
```sh
$ esc env set --file /path/to/file.txt myorg/myproj/myenv "mykey"
```
the `--file` flag also supports passing "-" to read from `stdin` so its consistent with the behavior of `--file` flag in `esc env edit`
```sh
$ cat /path/to/file.txt | esc env set --file - myorg/myproj/myenv
```
The flag can be combined with other flags. For example to store a file as a rawstring content and secret:
```sh
$ esc env set --secret --string --file /path/to/file.pem myorg/myproj/myenv "mykey"
```
To simplify reading file content, we fixed a bug where a new line is always being added at the end of the …
> Added support for passing values read from a file using --file

- CHANGELOG_PENDING.md
- cmd/esc/cli/cli_test.go
- cmd/esc/cli/client/apitype.go
- cmd/esc/cli/client/client.go
- cmd/esc/cli/env.go
- cmd/esc/cli/env_edit.go
- cmd/esc/cli/env_open.go
- cmd/esc/cli/env_run.go
- cmd/esc/cli/env_set.go
- cmd/esc/cli/env_version_rollback.go
- cmd/esc/cli/testdata/env-edit-editor-invalid-show-secrets-draft.yaml
- cmd/esc/cli/testdata/env-set-draft.yaml
- cmd/esc/cli/testdata/env-version-rollback-draft.yaml
- cmd/esc/cli/testdata/open-draft.yaml
- cmd/esc/cli/testdata/run-draft.yaml
- Update a draft via `--draft` for `env edit`, `env set`, and `env version rollback`
- Open a draft via `--draft` for `env run` and `env open`
Closes pulumi/pulumi-service#30603
> [Approvals] open and edit draft environments

- CHANGELOG_PENDING.md
- cmd/esc/cli/client/client.go
- cmd/esc/cli/client/client_test.go
Closes pulumi/pulumi-service#30757
We don't want these to be used by the CLI when the feature moves to GA in a PR that will be merged later.
> [Approvals] Use non preview routes

- schema/schema.go
- schema/schema_test.go
Propagate rotateonly deeply rather than shallowly. This should improve
the reliability of determining whether or not a particular schema has
rotate only semantics. Without these changes, the rotateonly semantics
of a property's schema would be lost when accessing the property's own
referenced schemas.
These changes also fix potential sharing issues that could occur when
marking property schemas as rotateonly by copying the property schema
instead of mutating it in place.
> schema: fix rotateonly propagation

- ast/environment.go
- ast/environment_test.go
- diags/diags.go
- diags/diags_test.go
- diags/utils.go
- diags/utils_test.go
- eval/eval.go
- eval/eval_test.go
- eval/rotation.go
- eval/testdata/eval/invalid-access/expected.json
- internal/spell/spell.go
- internal/spell/spell_test.go
- Enable the "no such field" diagnostic on the root environment
- When issuing a diagnostic for a missing property when evaluating a
property access, include an optional "did you mean" message
- Additionally, replace the `*RotationResult` bits with just
`RotationResult`, as it is already `nil`-able
With these changes, users will see warnings if they attempt to define
top-level keys in an environment that are neither `values` nor
`imports`.
> ast/eval: improve missing field diags
